### ISSUE TITLE
Cannot search R HTML documentation when jsonlite is installed

### ISSUE THREAD

**Issue by kfeinauer** [jeroen/jsonlite#196] opened 2017-08-22 20:17 UTC
When the jsonlite package is installed, search results that occur in the jsonlite package cause the R HTML documentation to break with the following error:

`Error in if (nchar(Outfile)) Outfile else File : 
  argument is not interpretable as logical`

Steps to reproduce:
1. Install jsonlite package
2. Open R GUI
3. Start HTML help `help.start(update = FALSE, gui = "irrelevant", browser = getOption("browser"), remote = NULL)`
4. Search help for the following string: `tm`
5. The R http service serves up the error

When debugging, it appeared that the offending statement was this line: https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/library/tools/R/toHTML.R#L173

It looks like this is blowing up because the `vignettes.rds` file in the meta directory contains a listing for `json-mapping.pdf.asis`, which doesn't match the expected topic `json-mapping.pdf`. That happens here: https://github.com/wch/r-source/blob/871172dfa2798ea401be4982c85a4653a0144de8/src/library/tools/R/dynamicHelp.R#L143.

Arguably, R should not blow up the entire query when it comes across an error in a package, but they have turned off public bug reporting so I could not file an issue there.

**Comment by jeroen** [comment] 2017-08-22 20:22
I think this is a bug in [R.rsp](https://github.com/HenrikBengtsson/R.rsp). The problem appears for each package that has a vignette using the vignette engine from R.rsp: `%\VignetteEngine{R.rsp::asis}`.

@HenrikBengtsson ?

**Comment by kevinushey** [comment] 2017-08-22 20:51
Looks like you're right -- I see the same issue when the `R.rsp` package is installed, which also provides a number of vignettes built from `rsp` files. E.g.

```R
install.packages("R.rsp")
options(help_type = "html")
??rsp
```

will end up serving a page with the contents:

```
Error in if (nchar(Outfile)) Outfile else File : 
  argument is not interpretable as logical
```

This error is emitted from here: https://github.com/wch/r-source/blob/118d3850054219eaab7ffe321349ceeeea88433d/src/library/tools/R/toHTML.R#L173

Note that the vignette table built by R has a bunch of NA entries:

```R
install.packages("R.rsp")
options(help_type = "html")
debugonce(tools:::makeVignetteTable)
??rsp
```

```
Browse[2]> vignettes
     Package    File               Title                                                        PDF                 R
[1,] "R.rsp"    NA                 NA                                                           NA                  NA
[2,] "R.rsp"    NA                 NA                                                           NA                  NA
[3,] "R.rsp"    NA                 NA                                                           NA                  NA
[4,] "R.rsp"    NA                 NA                                                           NA                  NA
[5,] "R.rsp"    NA                 NA                                                           NA                  NA
```

**Comment by HenrikBengtsson** [comment] 2017-08-23 12:51
Thanks. I can reproduce in R 3.4.1 on Linux. This must be something recent in R, because I'm pretty sure that HTML-based `help.search()` did work in the past for me.  I'll try to investigate asap (travelling right now).  This can hopefully be fixed in R.rsp, but should probably be protected/fixed also in core R / tools.

**Comment by HenrikBengtsson** [comment] 2017-08-23 13:47
I managed to dig a bit deeper.  I'm moving the troubleshooting over to https://github.com/HenrikBengtsson/R.rsp/issues/27 and will continue there.  I'll report back here when I have something useful to share.

**Comment by jeroen** [comment] 2017-08-24 10:26
--> https://github.com/HenrikBengtsson/R.rsp/issues/27

**Closed by jeroen** 2017-08-24 10:26 UTC

**Comment by HenrikBengtsson** [comment] 2017-08-29 23:22
FYI, I'm quite confident that this is a bug in R (https://github.com/HenrikBengtsson/R.rsp/issues/27).  I just sent a bug report with a patch to R-devel (https://stat.ethz.ch/pipermail/r-devel/2017-August/074834.html).

**Comment by jeroen** [comment] 2017-08-30 09:21
OK perfect thanks for the quick response. I suppose there is no temporary workaround possible in `R.rsp` to make this work in R 3.4.1?

**Comment by HenrikBengtsson** [comment] 2017-08-30 19:24
Nah... unfortunately I don't think it's possible to work around it - the bug is in R and independent of R.rsp per se - R.rsp just happens to make use of the possibility to have vignette file names with more than one extension.

The only way I can see to hack it (if it takes forever to fix this in R) is to have the 'R.rsp::asis' engine (to also) recognize `*.pdfasis` (generating `*.pdf`).  Even with such support, it would require all package that use such vignettes to be updated.

**Comment by HenrikBengtsson** [comment] 2017-08-31 19:06
UPDATE: Fixed in [R-devel (rev 73170)](https://github.com/wch/r-source/commit/be85b05ff2f9f4149d328c0923f8f4b21837bb14).  Let's hope it'll also make it into R 3.4.2 (2017-09-28)

**Comment by jeroen** [comment] 2017-08-31 19:17
Thanks!

**Comment by kevinushey** [comment] 2017-08-31 20:13
Awesome! Thanks for hunting that down @HenrikBengtsson!
