### ISSUE TITLE
stream_out() with small pagesize closes connection prematurely?

### ISSUE THREAD

**Issue by alexpghayes** [jeroen/jsonlite#315] opened 2020-05-12 01:59 UTC
I don't understand connections well enough to understand if this is expected behavior, but my impression is that this is a bug.

``` r
library(jsonlite)
#> Warning: package 'jsonlite' was built under R version 3.6.3

data_file <- tempfile()

download.file(
  "https://s3-us-west-2.amazonaws.com/ai2-s2-research-public/open-corpus/2020-04-10/sample-S2-records.gz",
  destfile = data_file
)

length(readLines(data_file))
#> [1] 100

results_file <- tempfile()

outfile <- file(results_file)

pg <- 10

handler <- function(df) {
  stream_out(df, outfile, pagesize = pg)
}

stream_in(
  gzfile(data_file),
  handler = handler,
  pagesize = pg
)
#> using a custom handler function.
#> opening gzfile input connection.
#> opening file output connection.
#> Processed 10 rows...Complete! Processed total of 10 rows.
#> closing file output connection.
#>  Found 10 records...
#> Error in isOpen(con, "w"): invalid connection
#> closing gzfile input connection.

# readLines(results_file)
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by alexpghayes** [comment] 2020-05-12 02:18
It looks like the issue is passing `pagesize` to `stream_out`.

``` r
library(jsonlite)
#> Warning: package 'jsonlite' was built under R version 3.6.3

data_file <- tempfile()

download.file(
  "https://s3-us-west-2.amazonaws.com/ai2-s2-research-public/open-corpus/2020-04-10/sample-S2-records.gz",
  destfile = data_file
)

length(readLines(data_file))
#> [1] 100

results_file <- tempfile()
outfile <- file(results_file, open = "wb")

handler <- function(df) {
  stream_out(df, outfile)
}

stream_in(
  gzfile(data_file),
  handler = handler,
  pagesize = 10
)
#> using a custom handler function.
#> opening gzfile input connection.
#> Complete! Processed total of 10 rows.
#>  Found 10 records...Complete! Processed total of 10 rows.
#>  Found 20 records...Complete! Processed total of 10 rows.
#>  Found 30 records...Complete! Processed total of 10 rows.
#>  Found 40 records...Complete! Processed total of 10 rows.
#>  Found 50 records...Complete! Processed total of 10 rows.
#>  Found 60 records...Complete! Processed total of 10 rows.
#>  Found 70 records...Complete! Processed total of 10 rows.
#>  Found 80 records...Complete! Processed total of 10 rows.
#>  Found 90 records...Complete! Processed total of 10 rows.
#>  Found 100 records...
#> closing gzfile input connection.

length(readLines(results_file))
#> Warning in readLines(results_file): incomplete final line found on 'C:
#> \Users\alex\AppData\Local\Temp\RtmpIfFxGb\file2abc62f93c8e'
#> [1] 100
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by alexpghayes** [comment] 2020-05-12 02:49
I played around with this some more and found more weird things I didn't understand -- `pagesize` may be misleading in the above

**Comment by jeroen** [comment] 2020-05-12 07:19
In your first example, the issue is that you forget to open the `outfile`. If you don't open `outfile` then `writeLines()` will automatically open+close it the first time you use it. So therefore at the second write, the connection object has already been closed.

**Closed** 2020-05-12 07:25 UTC

**Comment by alexpghayes** [comment] 2020-05-12 16:04
Thank you!
